// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeg6ISnkWwMKcFXOZz6gSGfhbMahJukE',
    appId: '1:231067119609:web:03612680314abdacda9728',
    messagingSenderId: '231067119609',
    projectId: 'books-20717',
    authDomain: 'books-20717.firebaseapp.com',
    storageBucket: 'books-20717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAFky9InDBxxuEWaVcirfln8gbjc8zmM',
    appId: '1:231067119609:android:eb322821a1bcd24fda9728',
    messagingSenderId: '231067119609',
    projectId: 'books-20717',
    storageBucket: 'books-20717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxpbf5Pj6le5jG0bNBcqZTCWr8XfaNV2I',
    appId: '1:231067119609:ios:15edb0a2b8226998da9728',
    messagingSenderId: '231067119609',
    projectId: 'books-20717',
    storageBucket: 'books-20717.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );
}
